### PR TITLE
Update stocks.json

### PR DESCRIPTION
**Pull request by scottrobel**
Removed duplicate and delisted stocks

### CODE REVIEW

**Comment by RayBB** [comment]
thanks for opening this. Do you mind sharing how you generated that list?

**Comment by RayBB** [comment]
@scottrobel can you share the code to generate this list?

**Comment by SirMonkMan** [comment]
Hi Ray

I've update the list and wrote a powershell script to generate the .js file

**Review by SirMonkMan — CHANGES_REQUESTED** [review]
This is no longer required as it is now out of date

**Pull request closed without merging**
